config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#show', defaults: { title: 'About' }, as: :about
  get '/contact', to: 'static_pages#show', defaults: { title: 'Contact' }, as: :contact
  get 'home/index'
  get 'products/index'
  get 'products/show'
  get 'categories/index'
  get 'categories/show'
  root "home#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/static_pages/:title', to: 'static_pages#show', as: :static_page
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :categories do
    resources :products
  end
  resources :products
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

 def self.ransackable_attributes(auth_object = nil)
    ["id", "email", "created_at", "updated_at"]
    # 如果需要更多属性进行搜索，请根据你的需求添加到数组中
  end

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "id_value", "name", "sub_category", "sub_category_href", "updated_at"]
  end

  has_many :products, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order_item_tax.rb
class OrderItemTax < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  def self.ransackable_associations(auth_object = nil)
    ["category"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "img_src", "name", "price", "product_link", "product_link_href", "updated_at"]
  end
  belongs_to :category
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "title", "updated_at"]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
end

app/models/tax_type.rb
class TaxType < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
# app/controllers/products_controller.rb

class ProductsController < ApplicationController
  before_action :find_category

  def index
    @products = @category.products
  end

  private

  def find_category
    @category = Category.find(params[:category_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Category not found."
    redirect_to categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sk</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/css/bootstrap.min.css', integrity: '...', crossorigin: 'anonymous' %>
  
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Sk</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact">Contact</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <main class="container mt-4">
      <%= yield %>
    </main>

    <footer class="bg-light text-center text-lg-start mt-4">
      <div class="container p-4">
        <div class="row">
          <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
            <h5 class="text-uppercase">Sk</h5>
            <p>
              This is a sample application built with Ruby on Rails.
            </p>
          </div>

          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>
            <ul class="list-unstyled mb-0">
              <li class="nav-item">
    <li class="nav-item">
    <%= link_to "Home", root_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "About", about_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Contact", contact_path, class: "nav-link" %>
  </li>

                <li><%= link_to "Categories", categories_path, class: "text-blue-500 hover:text-blue-700" %></li>
                <li><%= link_to "Products", products_path, class: "text-blue-500 hover:text-blue-700" %></li>
                 <li class="nav-item">
          <%= link_to "Admin", admin_root_path, class: "nav-link" %>
        </li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Follow Us</h5>
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#" class="text-dark">Facebook</a>
              </li>
              <li>
                <a href="#" class="text-dark">Twitter</a>
              </li>
              <li>
                <a href="#" class="text-dark">Instagram</a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2024 Copyright:
        <a class="text-dark" href="/">Sk</a>
      </div>
    </footer>
  </body>
</html>